version: "2.0"
services:
  # Load Balancer
  calliope_lb:
    container_name: "calliope-lb"
    image: kderbyma/maple-tree-labs:archi-lb_latest
    restart: always
    volumes:
      - "./load-balancer/certs:/etc/letsencrypt"
    depends_on:
      - "calliope_portal"
      - "calliope_ep"
    links:
      - "calliope_ep:calliope_ep"
      - "calliope_portal:calliope_portal"
    build:
      context: ./load-balancer/
    ports:
      - "10007:80"
    environment:
      API_PORT: ${API_PORT}
      EP_PORT: ${EP_PORT}
  # Database
  calliope_db:
    container_name: "calliope-db"
    image: kderbyma/maple-tree-labs:archi-db_latest
    build:
      context: ./database/
    restart: always
    ports:
      - "${DB_PORT}:5432"
    # volumes:
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
  # Etherpad API Endpoint (Behind Load Balancer)
  calliope_ep:
    container_name: "calliope-ep"
    image: kderbyma/maple-tree-labs:archi-ep_latest
    restart: always
    depends_on:
      - "calliope_db"
    build:
      context: ./etherpad/
    ports:
      - "${EP_PORT}:9001"
    links:
      - "calliope_db:calliope_db"
    command: []
    environment:
      NODE_ENV: ${NODE_ENV}
      DEBIAN_FRONTEND: noninteractive
      TZ: America/Edmonton
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST_DOCKER}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      EP_API_KEY: ${EP_API_KEY}
      EP_ADMIN_PASS: ${EP_ADMIN_PASS}
  # Main API / Portal for calliope
  calliope_portal:
    container_name: "calliope-portal"
    image: kderbyma/maple-tree-labs:calliope_latest
    restart: always
    build:
      context: ./server/
    depends_on:
      - "calliope_db"
    links:
      - "calliope_db:calliope_db"
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - "./server/build:/opt/calliope/build"
      - "./server/node_modules:/opt/calliope/node_modules"
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST_DOCKER}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      PUBLIC_URL: ${PUBLIC_URL}
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
      EP_API_KEY: ${EP_API_KEY}
      EP_HOST: ${EP_HOST_DOCKER}
      EP_PORT: ${EP_PORT}
