/*                                                 *\
** ----------------------------------------------- **
**             Calliope - Site Generator   	       **
** ----------------------------------------------- **
**  Copyright (c) 2020-2021 - Kyle Derby MacInnis  **
**                                                 **
**    Any unauthorized distribution or transfer    **
**       of this work is strictly prohibited.      **
**                                                 **
**               All Rights Reserved.              **
** ----------------------------------------------- **
\*                                                 */

// Use Tileset
import Tiles from "../tilesets/sewer.tiles";
// Map Information
export default {
  bounds: [0, 0, 17, 10],
  tileset: "sewer",
  // (0,0) -> (17,10) (X, Y) (10 Rows x 17 Column)
  cells: [
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.NLW_CORNER,
      Tiles.N_WALL,
      Tiles.N_WALL,
      Tiles.N_WALL,
      Tiles.NRW_CORNER,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.NLW_CORNER,
      Tiles.NLW_COLUMN,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.NRW_COLUMN,
      Tiles.NRW_CORNER,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.L_WALL,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.R_WALL,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.L_WALL,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.R_WALL,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.L_WALL,
      Tiles.NW_NPIT,
      Tiles.NW_NPIT,
      Tiles.N_STAIRWALL,
      Tiles.NW_NPIT,
      Tiles.NW_NPIT,
      Tiles.R_WALL,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.NLW_CORNER,
      Tiles.N_WALL,
      Tiles.N_WALL,
      Tiles.N_WALL,
      Tiles.NLW_LAVA_COLUMN,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.N_STAIR,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.NRW_LAVA_COLUMN,
      Tiles.N_WALL,
      Tiles.N_WALL,
      Tiles.N_WALL,
      Tiles.NRW_CORNER,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.NLW_CORNER,
      Tiles.NLW_COLUMN,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.LW_LPIT,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.V_WALKWAY,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.RW_RPIT,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.NRW_COLUMN,
      Tiles.NRW_CORNER,
    ],
    ...[
      Tiles.L_WALL,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.LW_LPIT,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.V_WALKWAY,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.RW_RPIT,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.R_WALL,
    ],
    ...[
      Tiles.L_WALL,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.L_STAIRWALL,
      Tiles.L_STAIR,
      Tiles.H_WALKWAY,
      Tiles.H_WALKWAY,
      Tiles.C_WALKWAY,
      Tiles.H_WALKWAY,
      Tiles.H_WALKWAY,
      Tiles.R_STAIR,
      Tiles.R_STAIRWALL,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.R_WALL,
    ],
    ...[
      Tiles.L_WALL,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.LW_LPIT,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.V_WALKWAY,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.RW_RPIT,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.R_WALL,
    ],
  ],
  // Sprites and Objects to be Loaded in the Scene & their Starting Points
  sprites: [
    { id: "e2", type: "monsters/air_elemental", pos: [8, 2, 0], facing: 8 },
    { id: "e3", type: "monsters/fire_elemental", pos: [2, 8, 0], facing: 1 },
    { id: "e4", type: "monsters/water_elemental", pos: [14, 8, 0], facing: 4 },
    { id: "spurt1", type: "effects/lavaspurt", pos: [10, 7, -1.5], facing: 2 },
    { id: "spurt2", type: "effects/lavaspurt", pos: [9, 6, -1.5], facing: 2 },
    { id: "spurt3", type: "effects/lavaspurt", pos: [10, 5, -1.5], facing: 2 },
    { id: "spurt4", type: "effects/lavaspurt", pos: [7, 6, -1.5], facing: 2 },
    { id: "spurt5", type: "effects/lavaspurt", pos: [6, 7, -1.5], facing: 2 },
    { id: "spurt6", type: "effects/lavaspurt", pos: [6, 9, -1.5], facing: 2 },
    { id: "spurt8", type: "effects/lavaspurt", pos: [9, 9, -1.5], facing: 2 },
    { id: "player", type: "characters/player", pos: [8, 8, -1], facing: 8 },
  ],
  // TODO - Add Scripts / Triggers for the Scene
  //
  // TODO - Add in Scenes / Dialogue
  //
};
