/*                                                 *\
** ----------------------------------------------- **
**             Calliope - Site Generator   	       **
** ----------------------------------------------- **
**  Copyright (c) 2020-2021 - Kyle Derby MacInnis  **
**                                                 **
**    Any unauthorized distribution or transfer    **
**       of this work is strictly prohibited.      **
**                                                 **
**               All Rights Reserved.              **
** ----------------------------------------------- **
\*                                                 */

// Tileset
import Tiles from "../tilesets/sewer.tiles";
// Map
export default {
  bounds: [0, 10, 17, 19],
  tileset: "sewer",
  // (0,10) -> (17,19) (X, Y) (9 Rows x 17 Column)
  cells: [
    ...[
      Tiles.SLW_CORNER,
      Tiles.SLW_COLUMN,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.LW_LPIT,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.V_WALKWAY,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.RW_RPIT,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.SRW_COLUMN,
      Tiles.SRW_CORNER,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.SLW_CORNER,
      Tiles.S_WALL,
      Tiles.S_WALL,
      Tiles.S_WALL,
      Tiles.SLW_LAVA_COLUMN,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.S_STAIR,
      Tiles.LAVA,
      Tiles.LAVA,
      Tiles.SRW_LAVA_COLUMN,
      Tiles.S_WALL,
      Tiles.S_WALL,
      Tiles.S_WALL,
      Tiles.SRW_CORNER,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.L_WALL,
      Tiles.SW_SPIT,
      Tiles.SW_SPIT,
      Tiles.S_STAIRWALL,
      Tiles.SW_SPIT,
      Tiles.SW_SPIT,
      Tiles.R_WALL,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.L_WALL,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.R_WALL,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.L_WALL,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.R_WALL,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.SLW_CORNER,
      Tiles.SLW_COLUMN,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.FLOOR,
      Tiles.SRW_COLUMN,
      Tiles.SRW_CORNER,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.SLW_CORNER,
      Tiles.S_WALL,
      Tiles.S_WALL,
      Tiles.S_WALL,
      Tiles.SRW_CORNER,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
    ...[
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
      Tiles.EMPTY,
    ],
  ],
  // Sprites and Objects to be Loaded in the Scene & their Starting Points
  sprites: [
    { id: "e1", type: "monsters/water_elemental", pos: [8, 13, 0], facing: 2 },
    { id: "spurt7", type: "effects/lavaspurt", pos: [7, 10, -1.5], facing: 2 },
    { id: "spurt9", type: "effects/lavaspurt", pos: [10, 10, -1.5], facing: 2 },
  ],
};
